import * as SharedTypes from '@proma/shared'
import * as ElectronTypes from '../../../../types'
import { UPDATER_IPC_CHANNELS } from '../../updater/updater-types'

export type WebRemoteChannelLevel = 'read' | 'session' | 'workspace' | 'write' | 'confirm' | 'denied'
export type WebRemoteScope = 'none' | 'session' | 'workspace'

export interface WebRemoteChannelPolicyEntry { level: WebRemoteChannelLevel; scope: WebRemoteScope; rationale: string }

function channelValues(value: unknown): string[] {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return []
  return Object.values(value).filter((item): item is string => typeof item === 'string')
}

const EXPORTED_CHANNELS = new Set<string>([
  ...Object.entries(SharedTypes).filter(([name]) => name.endsWith('IPC_CHANNELS')).flatMap(([, value]) => channelValues(value)),
  ...Object.entries(ElectronTypes).filter(([name]) => name.endsWith('IPC_CHANNELS')).flatMap(([, value]) => channelValues(value)),
  ...channelValues(UPDATER_IPC_CHANNELS),
])

const RUNTIME_LITERAL_CHANNELS = new Set(['file:exists-batch', 'file:office-to-html', 'file:prepare-pdf-preview', 'file:read-binary-base64', 'file:resolve-and-read', 'file:resolve-html-preview-path', 'file:resolve-markdown-media', 'file:resolve-path', 'file:write-text', 'migration:open-data-folder', 'web-remote:admin-get', 'web-remote:admin-save', 'web-remote:admin-pair', 'web-remote:admin-revoke', 'web-remote:admin-push-test', 'web-remote:admin-push-delete'])

/** Explicit reviewed table. Do not replace this with runtime regex inference. */
export const WEB_REMOTE_CHANNEL_POLICY: Readonly<Record<string, WebRemoteChannelPolicyEntry>> = Object.freeze({
  "web-remote:admin-get": { level: "denied", scope: "none", rationale: "仅桌面远程连接设置使用，手机禁止读取管理信息。" },
  "web-remote:admin-save": { level: "denied", scope: "none", rationale: "仅桌面远程连接设置使用，手机禁止修改手机访问配置。" },
  "web-remote:admin-pair": { level: "denied", scope: "none", rationale: "仅桌面远程连接设置使用，手机禁止生成配对码。" },
  "web-remote:admin-revoke": { level: "denied", scope: "none", rationale: "仅桌面远程连接设置使用，手机禁止撤销设备。" },
  "web-remote:admin-push-test": { level: "denied", scope: "none", rationale: "仅桌面设置发送测试通知，手机桥接禁止调用。" },
  "web-remote:admin-push-delete": { level: "denied", scope: "none", rationale: "仅桌面设置删除手机推送订阅，手机桥接禁止调用。" },
  "agent-island:mark-session-viewed": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:active-sessions-snapshot": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:active-worktree-updated": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:add-worktree-repo": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:approve-workspace-project-knowledge-maintenance": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:ask-user:respond": { level: "session", scope: "session", rationale: "响应仅允许当前远程授权工作区内的待处理会话请求。" },
  "agent:attach-directory": { level: "denied", scope: "none", rationale: "状态变更只允许在已授权会话/工作区内执行。" },
  "agent:attach-file": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:attach-workspace-directory": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:attach-workspace-file": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:batch-import-skills-from-workspaces": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:browser-state-changed": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:browser-tab-focused": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:cancel-queued-message": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:capabilities-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:check-paths-type": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:close-browser": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:close-browser-tab": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:confirm-working-done": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:confirm-workspace-memory-window-close": { level: "denied", scope: "none", rationale: "会在 Mac 上开窗、开应用或改项目根，手机端禁止。" },
  "agent:count-archived-sessions": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:create-browser-tab": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:create-project": { level: "denied", scope: "none", rationale: "状态变更只允许在已授权会话/工作区内执行。" },
  "agent:create-session": { level: "session", scope: "workspace", rationale: "仅允许在远程授权工作区中创建会话；新建会话不要求预先存在的 sessionId。" },
  "agent:create-skill-entry": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:create-workspace": { level: "confirm", scope: "none", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:delete-file": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:delete-mcp": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:delete-mcp-credential": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:delete-session": { level: "confirm", scope: "session", rationale: "会删除、迁移、截断或立即执行外部任务，必须使用一次性手机确认标记。" },
  "agent:delete-skill": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:delete-skill-entry": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:delete-workspace": { level: "confirm", scope: "workspace", rationale: "会删除、迁移、截断或立即执行外部任务，必须使用一次性手机确认标记。" },
  "agent:detach-directory": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:detach-file": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:detach-workspace-directory": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:detach-workspace-file": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:enqueue-queued-message": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:exit-plan-mode:respond": { level: "session", scope: "session", rationale: "响应仅允许当前远程授权工作区内的待处理会话请求。" },
  "agent:fork-session": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:generate-title": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:get-browser-state": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:get-capabilities": { level: "read", scope: "workspace", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:get-cli-integration-statuses": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:get-default-skill-slugs": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:get-mcp-config": { level: "read", scope: "workspace", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:get-other-workspace-skills": { level: "read", scope: "workspace", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:get-pending-requests": { level: "read", scope: "none", rationale: "只读恢复快照；返回值按远程允许工作区过滤。" },
  "agent:get-pi-reasoning-capability": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:get-queued-messages": { level: "read", scope: "session", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:get-sdk-messages": { level: "read", scope: "session", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:get-session-path": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:get-skills": { level: "read", scope: "workspace", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:get-skills-dir": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:get-workspace-attached-files": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:get-workspace-directories": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:get-workspace-files-path": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:get-workspace-memory-summary": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:get-worktree-repos": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:go-back-browser": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:go-forward-browser": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:import-skill-from-workspace": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:install-mcp-and-validate": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:list-active-sessions": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:list-archived-sessions": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:list-attached-directory": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:list-browser-tabs": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:list-directory": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:list-sessions": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:list-skill-files": { level: "read", scope: "workspace", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:list-workspace-auto-memory-files": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:list-workspaces": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:migrate-chat-to-agent": { level: "denied", scope: "none", rationale: "状态变更只允许在已授权会话/工作区内执行。" },
  "agent:minimize-browser": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:move-attached-file": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:move-file": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:move-queued-message": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:move-session-to-workspace": { level: "confirm", scope: "workspace", rationale: "会删除、迁移、截断或立即执行外部任务，必须使用一次性手机确认标记。" },
  "agent:navigate-browser": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:open-browser": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:open-file": { level: "denied", scope: "none", rationale: "会在 Mac 上开窗、开应用或改项目根，手机端禁止。" },
  "agent:open-file-or-folder-dialog": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:open-folder-dialog": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:open-folder-in-terminal": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:open-skill-folder": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:open-workspace-memory-window": { level: "denied", scope: "none", rationale: "会在 Mac 上开窗、开应用或改项目根，手机端禁止。" },
  "agent:permission:respond": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:promote-queued-message": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:queue-message": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:queued-message-status": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:read-attached-file": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:read-skill-content": { level: "read", scope: "workspace", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:read-skill-file": { level: "read", scope: "workspace", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:read-workspace-agents-md": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:read-workspace-auto-memory-file": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:refresh-mcp-connections": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:relink-workspace-project-root": { level: "denied", scope: "none", rationale: "会在 Mac 上开窗、开应用或改项目根，手机端禁止。" },
  "agent:reload-browser": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:remove-worktree-repo": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:rename-attached-file": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:rename-file": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:rename-skill-entry": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:reorder-workspaces": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:restore-workspace-project-root": { level: "denied", scope: "none", rationale: "会在 Mac 上开窗、开应用或改项目根，手机端禁止。" },
  "agent:rewind-session": { level: "confirm", scope: "session", rationale: "会删除、迁移、截断或立即执行外部任务，必须使用一次性手机确认标记。" },
  "agent:save-files-to-session": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:save-files-to-workspace": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:save-mcp-api-key": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:save-mcp-config": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:save-mcp-oauth-client-secret": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:search-messages": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:search-session-references": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:search-workspace-files": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:select-browser-tab": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:send-message": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:set-active-worktree": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:set-browser-layout": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:set-cli-integration-enabled": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:set-mcp-enabled-and-validate": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:set-visible-stream-session": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:show-attached-in-folder": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:show-in-folder": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:start-mcp-oauth": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:start-workspace-memory-watch": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:stop": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:stop-workspace-memory-watch": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:stream:complete": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:stream:error": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:stream:event": { level: "session", scope: "session", rationale: "会话流事件（SDK 消息、增量、审批/提问/计划事件）只镜像给该会话所属工作区已授权的设备；内容与该会话可读历史等价。" },
  "agent:submit-or-enqueue-message": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:test-mcp-server": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:title-updated": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:toggle-archive": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:toggle-pin": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:toggle-skill": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:toggle-star": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:update-session-codex-fast-mode": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:update-session-model": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:update-session-permission-mode": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:update-session-reasoning-level": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:update-skill-from-source": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:update-title": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "agent:update-workspace": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:workspace-files-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:workspace-memory-file-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "agent:workspace-memory-window-close-requested": { level: "denied", scope: "none", rationale: "会在 Mac 上开窗、开应用或改项目根，手机端禁止。" },
  "agent:workspace-memory-window-open-file": { level: "denied", scope: "none", rationale: "会在 Mac 上开窗、开应用或改项目根，手机端禁止。" },
  "agent:workspace-memory-window-ready": { level: "denied", scope: "none", rationale: "会在 Mac 上开窗、开应用或改项目根，手机端禁止。" },
  "agent:write-clipboard-preview": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "agent:write-skill-content": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:write-skill-file": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "agent:write-workspace-agents-md": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "agent:write-workspace-auto-memory-file": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "app-icon:set": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "automation:changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "automation:create": { level: "confirm", scope: "none", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "automation:delete": { level: "confirm", scope: "none", rationale: "会立即执行或删除定时任务，必须一次性确认。" },
  "automation:list": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "automation:run-now": { level: "confirm", scope: "none", rationale: "会立即执行或删除定时任务，必须一次性确认。" },
  "automation:toggle": { level: "confirm", scope: "none", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "automation:update": { level: "confirm", scope: "none", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "channel:codex-oauth-cancel": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:codex-oauth-device-code": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "channel:codex-oauth-login": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:create": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:decrypt-key": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:delete": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:fetch-models": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:get-plan-quota": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "channel:github-copilot-oauth-cancel": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:github-copilot-oauth-device-code": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "channel:github-copilot-oauth-login": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:list": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "channel:test": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:test-direct": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:update": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:xai-oauth-cancel": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "channel:xai-oauth-device-code": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "channel:xai-oauth-login": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "chat-tool:create-custom": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "chat-tool:custom-tool-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat-tool:delete-custom": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "chat-tool:get-all-tools": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "chat-tool:update-state": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:create-conversation": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "chat:delete-attachment": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "chat:delete-conversation": { level: "confirm", scope: "session", rationale: "会删除、迁移、截断或立即执行外部任务，必须使用一次性手机确认标记。" },
  "chat:delete-message": { level: "confirm", scope: "session", rationale: "会删除、迁移、截断或立即执行外部任务，必须使用一次性手机确认标记。" },
  "chat:extract-attachment-text": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "chat:generate-title": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "chat:get-messages": { level: "read", scope: "session", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:get-messages-around": { level: "read", scope: "session", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:get-recent-messages": { level: "read", scope: "session", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:list-conversations": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:open-file-dialog": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "chat:read-attachment": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "chat:save-attachment": { level: "denied", scope: "none", rationale: "状态变更只允许在已授权会话/工作区内执行。" },
  "chat:save-image-as": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "chat:save-resource-file-as": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "chat:search-messages": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:search-session-messages": { level: "read", scope: "session", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:send-message": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "chat:stop-generation": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "chat:stream:chunk": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:stream:complete": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:stream:error": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "chat:stream:reasoning": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "chat:stream:tool-activity": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "chat:toggle-archive": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "chat:toggle-pin": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "chat:truncate-messages-from": { level: "confirm", scope: "session", rationale: "会删除、迁移、截断或立即执行外部任务，必须使用一次性手机确认标记。" },
  "chat:update-context-dividers": { level: "denied", scope: "none", rationale: "状态变更只允许在已授权会话/工作区内执行。" },
  "chat:update-conversation-model": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "chat:update-title": { level: "session", scope: "session", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "clipboard:write-text": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:get-bot-decrypted-secret": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:get-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:get-decrypted-secret": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:get-multi-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:get-multi-status": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:get-status": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:multi-status-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "dingtalk:remove-bot": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:save-bot-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:save-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:start-bot": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:start-bridge": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:status-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "dingtalk:stop-bot": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:stop-bridge": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dingtalk:test-connection": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "dock-badge:set-count": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "environment:check": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:get-bot-decrypted-secret": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:get-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:get-decrypted-secret": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:get-multi-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:get-multi-status": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:get-status": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:list-bindings": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:multi-status-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "feishu:register-app-cancel": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:register-app-qrcode": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:register-app-start": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:register-app-status": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:remove-binding": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:remove-bot": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:report-presence": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:save-bot-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:save-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:start-bot": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:start-bridge": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:status-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "feishu:stop-bot": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:stop-bridge": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:test-connection": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "feishu:update-binding": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "file:exists-batch": { level: "read", scope: "none", rationale: "只读文件存在性检查；所有目标 realpath 必须位于允许工作区项目根、workspace-files、附加目录或允许会话目录。" },
  "file:office-to-html": { level: "read", scope: "none", rationale: "只读 Office 预览转换；所有目标 realpath 必须位于允许工作区项目根、workspace-files、附加目录或允许会话目录。" },
  "file:prepare-pdf-preview": { level: "read", scope: "none", rationale: "只读 PDF 预览准备；所有目标 realpath 必须位于允许工作区项目根、workspace-files、附加目录或允许会话目录。" },
  "file:read-binary-base64": { level: "read", scope: "none", rationale: "只读二进制预览；所有目标 realpath 必须位于允许工作区项目根、workspace-files、附加目录或允许会话目录。" },
  "file:resolve-and-read": { level: "read", scope: "none", rationale: "只读文件预览；所有目标 realpath 必须位于允许工作区项目根、workspace-files、附加目录或允许会话目录。" },
  "file:resolve-html-preview-path": { level: "read", scope: "none", rationale: "只读 HTML 预览路径；所有目标 realpath 必须位于允许工作区项目根、workspace-files、附加目录或允许会话目录。" },
  "file:resolve-markdown-media": { level: "read", scope: "none", rationale: "只读 Markdown 媒体解析；所有目标 realpath 必须位于允许工作区项目根、workspace-files、附加目录或允许会话目录。" },
  "file:resolve-path": { level: "read", scope: "none", rationale: "只读文件路径解析；所有目标 realpath 必须位于允许工作区项目根、workspace-files、附加目录或允许会话目录。" },
  "file:write-text": { level: "confirm", scope: "none", rationale: "会写入项目文件；必须确认且所有目标 realpath/父目录必须位于允许工作区项目根、workspace-files、附加目录或允许会话目录。" },
  "git:get-diff-contents": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "git:get-file-diff": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "git:get-repo-status": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "git:get-unstaged-changes": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "git:get-untracked-content": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "git:get-worktree-changes": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "git:invalidate-diff-cache": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "git:list-worktrees": { level: "workspace", scope: "workspace", rationale: "参数必须能解析出 sessionId 或 workspaceId/slug，并校验其在远程允许范围内。" },
  "git:revert-file": { level: "confirm", scope: "workspace", rationale: "会删除、覆盖或批量变更数据，必须一次性确认；workspace 变更仍校验允许范围。" },
  "github-release:get-by-tag": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "github-release:get-latest": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "github-release:list": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "installer:cancel": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "installer:download": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "installer:launch": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "installer:manifest": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "installer:progress": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "migration:open-data-folder": { level: "denied", scope: "none", rationale: "会打开本机数据目录，手机端禁止。" },
  "planning:acknowledge-reminder": { level: "write", scope: "none", rationale: "规划数据写入不触发系统窗口、凭据或项目文件副作用；允许手机端直接写入。" },
  "planning:agent-operation": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "planning:changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "planning:connect-native-connection": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:create-calendar-event": { level: "write", scope: "none", rationale: "规划数据写入不触发系统窗口、凭据或项目文件副作用；允许手机端直接写入。" },
  "planning:create-group": { level: "write", scope: "none", rationale: "规划数据写入不触发系统窗口、凭据或项目文件副作用；允许手机端直接写入。" },
  "planning:create-todo": { level: "write", scope: "none", rationale: "规划数据写入不触发系统窗口、凭据或项目文件副作用；允许手机端直接写入。" },
  "planning:delete-calendar-event": { level: "confirm", scope: "none", rationale: "会删除规划数据，必须一次性确认。" },
  "planning:delete-group": { level: "confirm", scope: "none", rationale: "会删除规划数据，必须一次性确认。" },
  "planning:delete-todo": { level: "confirm", scope: "none", rationale: "会删除规划数据，必须一次性确认。" },
  "planning:disconnect-native-connection": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:get-native-sync-status": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:list-active-reminders": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "planning:list-calendar-events": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "planning:list-groups": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "planning:list-native-connection-targets": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:list-native-connections": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:list-native-sync-conflicts": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:list-native-sync-targets": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:list-sync-profiles": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:list-tags": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "planning:list-todos": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "planning:open-native-sync-privacy-settings": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:reminder-due": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "planning:request-native-sync-access": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:resolve-native-sync-conflict": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:save-sync-profile": { level: "denied", scope: "none", rationale: "macOS Calendar/Reminders 原生同步或凭据配置，手机端禁止。" },
  "planning:snooze-reminder": { level: "write", scope: "none", rationale: "规划数据写入不触发系统窗口、凭据或项目文件副作用；允许手机端直接写入。" },
  "planning:start-todo-agent": { level: "write", scope: "none", rationale: "规划数据写入不触发系统窗口、凭据或项目文件副作用；允许手机端直接写入。" },
  "planning:update-calendar-event": { level: "write", scope: "none", rationale: "规划数据写入不触发系统窗口、凭据或项目文件副作用；允许手机端直接写入。" },
  "planning:update-group": { level: "write", scope: "none", rationale: "规划数据写入不触发系统窗口、凭据或项目文件副作用；允许手机端直接写入。" },
  "planning:update-todo": { level: "write", scope: "none", rationale: "规划数据写入不触发系统窗口、凭据或项目文件副作用；允许手机端直接写入。" },
  "preview:get-detached-data": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "preview:open-detached": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "proxy:detect-system": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "proxy:get-settings": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "proxy:update-settings": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "quick-task:focus": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "quick-task:get-global-shortcut-registration-status": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "quick-task:hide": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "quick-task:reregister-global-shortcuts": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "quick-task:submit": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "runtime:get-status": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "runtime:reinit": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "scratch-pad:choose-export-path": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "scratch-pad:copy-image": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "scratch-pad:export": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "scratch-pad:load": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "scratch-pad:save": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "scratch-pad:save-sync": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "screenshot:capture": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "settings:get": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "settings:get-system-theme": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "settings:system-theme-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "settings:theme-settings-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "settings:update": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "settings:update-sync": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "shell:get-default-app-for-file": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "shell:open-external": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "shell:scan-editors": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "shell:show-item-in-folder": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "shell:system-open-file": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "slack:get-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "slack:get-manifest": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "slack:get-status": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "slack:remove-bot": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "slack:save-bot-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "slack:start-bot": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "slack:status-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "slack:stop-bot": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "slack:test-connection": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "storage:cleanup": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "storage:cleanup-temp": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "storage:get-stats": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "system-prompt:create": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "system-prompt:delete": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "system-prompt:get-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "system-prompt:set-default": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "system-prompt:update": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "system-prompt:update-append-setting": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "terminal:ack-output": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "terminal:agent-close": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "terminal:agent-open": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "terminal:create": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "terminal:exit": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "terminal:input": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "terminal:kill": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "terminal:output": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "terminal:resize": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "terminal:snapshot": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "tray:create-session": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "tray:open-agent-session": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "updater:cancel-idle-install": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "updater:check": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "updater:get-status": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "updater:install-when-idle": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "updater:status-changed": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "user-profile:get": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "user-profile:update": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:authorize-candidate": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:create-folder": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:create-untitled-file": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:create-untitled-file-in-folder": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:delete-file": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:get-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:list-candidates": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:list-files": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:read-file": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:rename-file": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:resolve-media": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:save-pasted-image": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:select": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:select-default": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:set-user-context": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "vault:write-file": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "voice-dictation:ack-insert-text": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:cancel": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:check-mic-permission": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:clear-preview-text": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:commit": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:get-settings": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:hide": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:indicator-state": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:insert-text": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:preview": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:preview-text": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:report-transcript": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:report-volume": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:request-mic-permission": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:resize": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:send-audio": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:shown": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:start": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:state": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:stop": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:test-connection": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:toggle": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:toggle-stop": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:transcript": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "voice-dictation:update-settings": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "wechat:get-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "wechat:get-status": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "wechat:logout": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "wechat:save-config": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "wechat:start-bridge": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "wechat:start-login": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "wechat:status-changed": { level: "read", scope: "none", rationale: "只读结果或状态事件；列表和设置结果在返回前按允许范围/敏感字段过滤。" },
  "wechat:stop-bridge": { level: "denied", scope: "none", rationale: "已登记但尚未完成人工复核，按最小权限默认拒绝。" },
  "window:close": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "window:is-focused": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "window:is-maximized": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "window:maximize": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "window:minimize": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "windows-agent-island:mouse-enter": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "windows-agent-island:mouse-leave": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "windows-agent-island:open-session": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "windows-agent-island:play-sound": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
  "windows-agent-island:push-snapshot": { level: "denied", scope: "none", rationale: "原生窗口、终端、凭据、设置写入或外部副作用，不向手机 renderer 暴露。" },
})

export function getWebRemoteChannelPolicy(channel: string): WebRemoteChannelPolicyEntry | undefined { return WEB_REMOTE_CHANNEL_POLICY[channel] }

export function getDeclaredWebRemoteChannels(): string[] { return [...new Set([...EXPORTED_CHANNELS, ...RUNTIME_LITERAL_CHANNELS])].sort() }

export function policySummary(): Record<WebRemoteChannelLevel, number> {
  const summary: Record<WebRemoteChannelLevel, number> = { read: 0, session: 0, workspace: 0, write: 0, confirm: 0, denied: 0 }
  for (const entry of Object.values(WEB_REMOTE_CHANNEL_POLICY)) summary[entry.level]++
  return summary
}
