const ALLOWED_ROLES = new Set(['user', 'assistant', 'tool', 'system', 'unknown'])

export function renderWebRemoteStatic(nonce: string): string {
  return `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#111827"><title>Proma Web Remote</title>
<style nonce="${nonce}">
:root{color-scheme:dark;font-family:system-ui,-apple-system,sans-serif;background:#111827;color:#f3f4f6}*{box-sizing:border-box}body{margin:0;max-width:900px;margin-inline:auto;padding:16px}button,input,textarea{font:inherit;border-radius:8px;border:1px solid #374151;background:#1f2937;color:inherit;padding:10px}button{cursor:pointer;background:#2563eb;border:0}.muted{color:#9ca3af}.card{background:#1f2937;border:1px solid #374151;border-radius:12px;padding:12px;margin:10px 0}.row{display:flex;gap:8px;align-items:center;justify-content:space-between}.messages{min-height:50vh;max-height:65vh;overflow:auto}.message{white-space:pre-wrap;margin:8px 0;padding:8px;border-radius:8px;background:#111827}.assistant{border-left:3px solid #60a5fa}.user{border-left:3px solid #34d399}.tool{border-left:3px solid #f59e0b}.system,.unknown{border-left:3px solid #9ca3af}.permission{border-left:3px solid #ef4444}.banner{padding:10px;border-radius:8px;background:#78350f;margin:10px 0}.status-running{color:#34d399}.status-idle{color:#9ca3af}.hidden{display:none}#pair{max-width:400px;margin:10vh auto}#input{width:100%;resize:vertical}.tool-line{font-size:.9em;color:#fbbf24;margin:8px 0}.permission pre{white-space:pre-wrap;overflow:auto;max-height:160px;background:#111827;padding:8px}.permission-actions{display:flex;gap:8px}.permission-actions button:last-child{background:#6b7280}
</style></head><body>
<section id="pair" class="card"><h1>Proma Web Remote</h1><p class="muted">输入桌面端生成的 6 位配对码。</p><input id="code" inputmode="numeric" maxlength="6" placeholder="配对码"><input id="label" placeholder="设备名称（可选）"><button id="pairBtn" type="button">配对</button><p id="pairError" class="muted"></p></section>
<section id="app" class="hidden"><div class="row"><h1>Proma</h1><div><span id="runStatus" class="status-idle">空闲</span><button id="refresh" type="button">刷新</button></div></div><div id="banner" class="banner hidden"></div><div id="sessions"></div><section id="detail" class="hidden"><div class="row"><h2 id="title"></h2><div><button id="stop" type="button">中止</button><button id="back" type="button">返回</button></div></div><div id="interactions"></div><div id="messages" class="messages"></div><div class="row"><textarea id="input" rows="2" placeholder="发送消息"></textarea><button id="send" type="button">发送</button></div></section></section>
<script nonce="${nonce}">
const $=id=>document.getElementById(id);const allowedRoles=new Set(['user','assistant','tool','system','unknown']);let sessions=[],workspaces=new Map(),current=null,ws=null,reconnectTimer=null,reconnectDelay=1000,streamNode=null,streamText='',manualClose=false;
function showPair(){manualClose=true;if(ws){ws.close();ws=null}current=null;$('pair').classList.remove('hidden');$('app').classList.add('hidden');}
function showApp(){$('pair').classList.add('hidden');$('app').classList.remove('hidden');}
function roleClass(role){return allowedRoles.has(role)?role:'unknown'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setBanner(text){$('banner').textContent=text||'';$('banner').classList.toggle('hidden',!text)}
function setRunning(running){$('runStatus').textContent=running?'运行中':'空闲';$('runStatus').className=running?'status-running':'status-idle';if(current)current.running=running}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(r.status===401){showPair()}if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||r.status);return r.status===204?null:r.json()}
function renderSessions(){const html=sessions.map(s=>{const workspace=workspaces.get(s.workspaceId)||'未分组';return '<div class="card row"><div><b>'+esc(s.title)+'</b><div class="muted">'+esc(workspace)+' · '+(s.running?'运行中':'空闲')+(s.hasPendingPermission?' · 待审批':'')+'</div></div><button type="button" data-session-id="'+esc(s.id)+'">打开</button></div>'}).join('');$('sessions').innerHTML=html;document.querySelectorAll('[data-session-id]').forEach(button=>button.addEventListener('click',()=>openSession(button.dataset.sessionId)))}
async function load(){workspaces=new Map((await api('/api/workspaces')).map(w=>[w.id,w.name]));sessions=await api('/api/sessions');renderSessions();if(current){const latest=sessions.find(s=>s.id===current.id);if(latest){current=latest;setRunning(latest.running)}}}
function messageHtml(m){const role=roleClass(m.role);const body=m.text||m.toolResult||m.toolInput||'';const tool=m.toolName?'<div class="muted">工具：'+esc(m.toolName)+'</div>':'';return '<div class="message '+role+'"><b>'+esc(role)+'</b>'+tool+'<div>'+esc(body)+'</div></div>'}
function renderMessages(messages){$('messages').innerHTML=messages.map(messageHtml).join('');$('messages').scrollTop=$('messages').scrollHeight;clearStream()}
async function refreshHistory(){if(!current)return;renderMessages(await api('/api/sessions/'+encodeURIComponent(current.id)+'/messages?limit=200'))}
function clearStream(){if(streamNode)streamNode.remove();streamNode=null;streamText=''}
function appendStream(text){if(!streamNode){streamNode=document.createElement('div');streamNode.className='message assistant';streamNode.innerHTML='<b>assistant</b><div></div>';$('messages').appendChild(streamNode)}streamText+=text;streamNode.lastElementChild.textContent=streamText;$('messages').scrollTop=$('messages').scrollHeight}
function addToolStatus(event){const node=document.createElement('div');node.className='tool-line';node.textContent='工具 '+event.toolName+'：'+(event.status==='started'?'执行中':'已完成');$('messages').appendChild(node);$('messages').scrollTop=$('messages').scrollHeight}
function upsertPermission(request){if(document.querySelector('[data-permission-id="'+CSS.escape(request.requestId)+'"]'))return;const card=document.createElement('div');card.className='card permission';card.dataset.permissionId=request.requestId;card.innerHTML='<b>需要审批：'+esc(request.toolName)+'</b><p>'+esc(request.description)+'</p><pre>'+esc(request.toolInput||request.command||'')+'</pre><div class="permission-actions"><button type="button" data-behavior="allow">允许</button><button type="button" data-behavior="deny">拒绝</button></div>';card.querySelectorAll('[data-behavior]').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;try{await api('/api/permissions/'+encodeURIComponent(request.requestId),{method:'POST',body:JSON.stringify({behavior:button.dataset.behavior})})}catch(error){button.disabled=false;setBanner(error.message)}}));$('interactions').appendChild(card)}
function removePermission(id){document.querySelector('[data-permission-id="'+CSS.escape(id)+'"]')?.remove()}
async function handleEvent(event){if(event.type==='ready')return;if(event.type==='run_started'){setRunning(true);return}if(event.type==='text_delta'){appendStream(event.text);return}if(event.type==='tool_status'){addToolStatus(event);return}if(event.type==='permission_request'){upsertPermission(event.request);return}if(event.type==='permission_resolved'){removePermission(event.requestId);return}if(event.type==='interaction_unavailable'){setBanner(event.message||'请在桌面处理');return}if(event.type==='sdk_message'){clearStream();if(event.message) $('messages').insertAdjacentHTML('beforeend',messageHtml(event.message));$('messages').scrollTop=$('messages').scrollHeight;return}if(event.type==='refresh_required'){await refreshHistory();return}if(event.type==='title_updated'){if(current){current.title=event.title;$('title').textContent=event.title}return}if(event.type==='run_completed'||event.type==='run_stopped'){setRunning(false);await Promise.all([refreshHistory(),load()])}}
function scheduleReconnect(){if(manualClose||!current||reconnectTimer)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;connect()},reconnectDelay);reconnectDelay=Math.min(30000,reconnectDelay*2)}
function connect(){if(!current)return;const old=ws;ws=null;if(old)old.close();manualClose=false;const socket=new WebSocket(location.origin.replace(/^http/,'ws')+'/api/stream');ws=socket;socket.addEventListener('open',()=>{reconnectDelay=1000;setBanner('');setRunning(Boolean(current?.running));socket.send(JSON.stringify({type:'subscribe',sessionIds:[current.id]}))});socket.addEventListener('message',event=>{try{void handleEvent(JSON.parse(event.data))}catch(error){setBanner('实时事件解析失败')}});socket.addEventListener('close',event=>{if(ws!==socket)return;ws=null;if(event.code===1008){showPair();return}scheduleReconnect()});socket.addEventListener('error',()=>{})}
async function openSession(id){current=sessions.find(s=>s.id===id);if(!current)return;$('title').textContent=current.title;$('detail').classList.remove('hidden');$('sessions').classList.add('hidden');$('interactions').innerHTML='';await refreshHistory();connect()}
$('pairBtn').addEventListener('click',async()=>{try{await api('/api/pair',{method:'POST',body:JSON.stringify({code:$('code').value,label:$('label').value})});showApp();await load()}catch(error){$('pairError').textContent=error.message}});
$('refresh').addEventListener('click',()=>{void load()});$('back').addEventListener('click',()=>{manualClose=true;const old=ws;ws=null;if(old)old.close();current=null;$('detail').classList.add('hidden');$('sessions').classList.remove('hidden')});$('stop').addEventListener('click',()=>{if(current)void api('/api/sessions/'+encodeURIComponent(current.id)+'/stop',{method:'POST'})});$('send').addEventListener('click',async()=>{if(!current)return;const value=$('input').value.trim();if(!value)return;$('input').value='';await api('/api/sessions/'+encodeURIComponent(current.id)+'/send',{method:'POST',body:JSON.stringify({message:value})});setRunning(true)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&current){void refreshHistory();if(!ws)connect()}});
(async()=>{try{await load();showApp()}catch{showPair()}})();
</script></body></html>`
}
