import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

describe('Web Remote listener recovery', () => {
  test('unknown stream/title triggers share the Web Remote active-only refresh path', () => {
    const source = readFileSync(join(import.meta.dir, 'useGlobalAgentListeners.ts'), 'utf8')
    const start = source.indexOf('const refreshUnknownAgentSession = async (sessionId: string): Promise<void> => {')
    const end = source.indexOf('\n    const recoverWebRemoteState', start)
    expect(start).toBeGreaterThanOrEqual(0)
    expect(end).toBeGreaterThan(start)
    const refresh = source.slice(start, end)
    expect(refresh).toContain('shouldRefreshUnknownAgentSession')
    expect(refresh).toContain('fetchAndMergeAgentSessionSnapshot()')
    expect(refresh).toContain('listActiveAgentSessions()')
    expect(refresh).toContain('mergeAgentSessionSnapshotWithChanges(prev, sessions, snapshotRevision, false)')
    expect(refresh).toContain('knownInvisibleSessionIds.add(sessionId)')

    const streamStart = source.indexOf('// 如果收到未知会话的事件')
    const streamEnd = source.indexOf('// Phase 2:', streamStart)
    expect(source.slice(streamStart, streamEnd)).toContain('refreshUnknownAgentSession(sessionId)')
    const titleStart = source.indexOf('// 外部桥接可能先发标题、后发 run-start；未知会话统一走 Web Remote active 去重策略。')
    const titleEnd = source.indexOf('const cleanupActiveWorktreeUpdated', titleStart)
    expect(source.slice(titleStart, titleEnd)).toContain('refreshUnknownAgentSession(sessionId)')
  })

  test('complete keeps the existing single history refresh path for mobile events', () => {
    const listenerSource = readFileSync(join(import.meta.dir, 'useGlobalAgentListeners.ts'), 'utf8')
    const viewSource = readFileSync(join(import.meta.dir, '../components/agent/AgentView.tsx'), 'utf8')
    const start = listenerSource.indexOf('const cleanupComplete = window.electronAPI.onAgentStreamComplete(')
    const end = listenerSource.indexOf('// ===== 3. 流式错误 =====', start)
    expect(start).toBeGreaterThanOrEqual(0)
    expect(end).toBeGreaterThan(start)
    const handler = listenerSource.slice(start, end)
    expect(handler).not.toContain('data.messages')
    expect((handler.match(/bumpRefresh\(\)\s*;?/g) ?? [])).toHaveLength(1)
    expect(viewSource).toContain('window.electronAPI.getAgentSessionSDKMessages(sessionId)')
    expect(viewSource).toContain('[sessionId, refreshVersion,')
  })
  test('reconciles stale local runs and refreshes each missing session once only on Web Remote reconnect', () => {
    const source = readFileSync(join(import.meta.dir, 'useGlobalAgentListeners.ts'), 'utf8')
    const start = source.indexOf('const recoverWebRemoteState = async (): Promise<void> => {')
    const end = source.indexOf('\n    }', start)
    const recovery = source.slice(start, end)
    expect(recovery).toContain('findMissingActiveAgentSessionIds(')
    expect(recovery).toContain('settleMissingAgentStreamState')
    expect(recovery).toContain('store.set(agentMessageRefreshAtom')
    expect(recovery).toContain('if (activeSessionId && !missingSessionIds.includes(activeSessionId))')
    expect(source).toContain('__PROMA_WEB_REMOTE_RECOVER = recoverWebRemoteState')
    expect(source).toContain('restoreActiveSnapshots(), restoreStoppedSessions()')
  })

  test('leaves the reconnect list snapshot to the sidebar resync listener', () => {
    const source = readFileSync(join(import.meta.dir, 'useGlobalAgentListeners.ts'), 'utf8')
    const start = source.indexOf('const recoverWebRemoteState = async (): Promise<void> => {')
    const end = source.indexOf('\n    }', start)
    expect(start).toBeGreaterThanOrEqual(0)
    expect(end).toBeGreaterThan(start)
    const recovery = source.slice(start, end)
    expect(recovery).toContain('restoreActiveSnapshots()')
    expect(recovery).toContain('restoreQueuedMessages()')
    expect(recovery).toContain('restorePendingRequests()')
    expect(recovery).not.toContain('restoreStoppedSessions()')
    expect(recovery).not.toContain('fetchAndMergeAgentSessionSnapshot()')
    expect(recovery).not.toMatch(/list(?:Active|Archived)?AgentSessions\(/)
  })
})
